### ISSUE TITLE
stilt job starter webpage stalls when entering longitude outside model domain

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/stiltweb#17]
Sometimes the stilt job starter webpage stalls when entering longitude or latitude outside the model domain (15W-35E, 33N-73N). But sometimes the behavior is ok, so the error cannot always be reproduced. Normal behavior is that cell turns red to indicate wrong entry but user can continue and revise numbers.

**Comment by ukarst** [comment]
Similar problems occur for latitude values with zero decimals.

**Comment by mirzov** [comment]
Fixed in d5f773c, 06cac5d, 8130385, 031fc71
