### ISSUE TITLE
Adapt STILT tools to ATMO ACCESS requirements: -allow submitting footprint jobs with flexpart and track usage for ATMO ACCESS VA service

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/stiltweb#23]

**Comment by mirzov** [comment]
Fixed in:
https://github.com/ICOS-Carbon-Portal/stiltweb/commit/af17e873cea85bf25a3072c8f096af8ec5a9a094
https://github.com/ICOS-Carbon-Portal/stiltweb/commit/e0db823d61f158f4ab6b74501855f8e9d3bfd0f4
https://github.com/ICOS-Carbon-Portal/stiltweb/commit/1b1565d4a6464ac7928c7f03545243be170c4800
