### ISSUE TITLE
Coordinates uses commas in some locales

### ISSUE THREAD

**Issue by jonathanthiry** [ICOS-Carbon-Portal/stiltweb#29]
String interpolation uses commas in some locales, like en_SE.

https://github.com/ICOS-Carbon-Portal/stiltweb/blob/de67f219731617b937a09844f1cda08b81671e12/stiltcluster/src/main/scala/se/lu/nateko/cp/stiltcluster/StiltSlot.scala#L30

**Comment by mirzov** [comment]
Fixed in 7afb6dc
